# Generated by Django 3.1.1 on 2020-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
